// Copyright (c) All contributors. All rights reserved. Licensed under the MIT license.

using System.Collections.Generic;

namespace Tinyhand.Generator;

internal static class FormatterCatalog
{
    internal static readonly Dictionary<string, string> Registrations = new()
    {
        { "System.Collections.Generic.List`1", "RegisterListFormatter" },
        { "System.Collections.Generic.LinkedList`1", "RegisterLinkedListFormatter" },
        { "System.Collections.Generic.Queue`1", "RegisterQueueFormatter" },
        { "System.Collections.Generic.Stack`1", "RegisterStackFormatter" },
        { "System.Collections.Generic.HashSet`1", "RegisterHashSetFormatter" },
        { "System.Collections.ObjectModel.ReadOnlyCollection`1", "RegisterReadOnlyCollectionFormatter" },
        { "System.Collections.Generic.IList`1", "RegisterInterfaceListFormatter2" },
        { "System.Collections.Generic.ICollection`1", "RegisterInterfaceCollectionFormatter2" },
        { "System.Collections.Generic.IEnumerable`1", "RegisterInterfaceEnumerableFormatter" },
        { "System.Collections.Generic.Dictionary`2", "RegisterDictionaryFormatter" },
        { "System.Collections.Generic.IDictionary`2", "RegisterInterfaceDictionaryFormatter" },
        { "System.Collections.Generic.SortedDictionary`2", "RegisterSortedDictionaryFormatter" },
        { "System.Collections.Generic.SortedList`2", "RegisterSortedListFormatter" },
        { "System.Linq.ILookup`2", "RegisterInterfaceLookupFormatter" },
        { "System.Linq.IGrouping`2", "RegisterInterfaceGroupingFormatter" },
        { "System.Collections.ObjectModel.ObservableCollection`1", "RegisterObservableCollectionFormatter" },
        { "System.Collections.ObjectModel.ReadOnlyObservableCollection`1", "RegisterReadOnlyObservableCollectionFormatter" },
        { "System.Collections.Generic.IReadOnlyList`1", "RegisterInterfaceReadOnlyListFormatter" },
        { "System.Collections.Generic.IReadOnlyCollection`1", "RegisterInterfaceReadOnlyCollectionFormatter" },
        { "System.Collections.Generic.ISet`1", "RegisterInterfaceSetFormatter" },
        { "System.Collections.Concurrent.ConcurrentBag`1", "RegisterConcurrentBagFormatter" },
        { "System.Collections.Concurrent.ConcurrentQueue`1", "RegisterConcurrentQueueFormatter" },
        { "System.Collections.Concurrent.ConcurrentStack`1", "RegisterConcurrentStackFormatter" },
        { "System.Collections.ObjectModel.ReadOnlyDictionary`2", "RegisterReadOnlyDictionaryFormatter" },
        { "System.Collections.Generic.IReadOnlyDictionary`2", "RegisterInterfaceReadOnlyDictionaryFormatter" },
        { "System.Collections.Concurrent.ConcurrentDictionary`2", "RegisterConcurrentDictionaryFormatter" },
        { "System.Lazy`1", "RegisterLazyFormatter" },
        { "System.Collections.Immutable.ImmutableArray`1", "RegisterImmutableArrayFormatter" },
        { "System.Collections.Immutable.ImmutableList`1", "RegisterImmutableListFormatter" },
        { "System.Collections.Immutable.ImmutableDictionary`2", "RegisterImmutableDictionaryFormatter" },
        { "System.Collections.Immutable.ImmutableHashSet`1", "RegisterImmutableHashSetFormatter" },
        { "System.Collections.Immutable.ImmutableSortedDictionary`2", "RegisterImmutableSortedDictionaryFormatter" },
        { "System.Collections.Immutable.ImmutableSortedSet`1", "RegisterImmutableSortedSetFormatter" },
        { "System.Collections.Immutable.ImmutableQueue`1", "RegisterImmutableQueueFormatter" },
        { "System.Collections.Immutable.ImmutableStack`1", "RegisterImmutableStackFormatter" },
        { "System.Collections.Immutable.IImmutableList`1", "RegisterInterfaceImmutableListFormatter" },
        { "System.Collections.Immutable.IImmutableDictionary`2", "RegisterInterfaceImmutableDictionaryFormatter" },
        { "System.Collections.Immutable.IImmutableQueue`1", "RegisterInterfaceImmutableQueueFormatter" },
        { "System.Collections.Immutable.IImmutableSet`1", "RegisterInterfaceImmutableSetFormatter" },
        { "System.Collections.Immutable.IImmutableStack`1", "RegisterInterfaceImmutableStackFormatter" },
        { "Arc.Collections.OrderedMap`2", "RegisterOrderedMapFormatter" },
        { "Arc.Collections.OrderedSet`1", "RegisterOrderedSetFormatter" },
        { "Arc.Collections.OrderedMultiMap`2", "RegisterOrderedMultiMapFormatter" },
        { "Arc.Collections.OrderedMultiSet`1", "RegisterOrderedMultiSetFormatter" },
        { "Arc.Collections.UnorderedMap`2", "RegisterUnorderedMapFormatter" },
        { "Arc.Collections.UnorderedSet`1", "RegisterUnorderedSetFormatter" },
        { "Arc.Collections.OrderedKeyValueList`2", "RegisterOrderedKeyValueListFormatter" },
        { "Arc.Collections.OrderedList`1", "RegisterOrderedListFormatter" },
        { "Arc.Collections.UnorderedList`1", "RegisterUnorderedListFormatter" },
        { "Arc.Collections.UnorderedLinkedList`1", "RegisterUnorderedLinkedListFormatter" },
        { "Arc.Collections.Utf16Hashtable`1", "RegisterUtf16HashtableFormatter" },
        { "System.Collections.Generic.KeyValuePair`2", "RegisterKeyValuePairFormatter" },
        { "Tinyhand.KeyValueList`2", "RegisterKeyValueListFormatter" },
        { "System.ArraySegment`1", "RegisterArraySegmentFormatter" },
        { "System.Memory`1", "RegisterMemoryFormatter" },
        { "System.ReadOnlyMemory`1", "RegisterReadOnlyMemoryFormatter" },
        { "System.Buffers.ReadOnlySequence`1", "RegisterReadOnlySequenceFormatter" },
        { "System.Nullable`1", "RegisterNullableFormatter" },
        { "System.Tuple`1", "RegisterTupleFormatter" },
        { "System.Tuple`2", "RegisterTupleFormatter" },
        { "System.Tuple`3", "RegisterTupleFormatter" },
        { "System.Tuple`4", "RegisterTupleFormatter" },
        { "System.Tuple`5", "RegisterTupleFormatter" },
        { "System.Tuple`6", "RegisterTupleFormatter" },
        { "System.Tuple`7", "RegisterTupleFormatter" },
        { "System.Tuple`8", "RegisterTupleFormatter" },
        { "System.ValueTuple`1", "RegisterValueTupleFormatter" },
        { "System.ValueTuple`2", "RegisterValueTupleFormatter" },
        { "System.ValueTuple`3", "RegisterValueTupleFormatter" },
        { "System.ValueTuple`4", "RegisterValueTupleFormatter" },
        { "System.ValueTuple`5", "RegisterValueTupleFormatter" },
        { "System.ValueTuple`6", "RegisterValueTupleFormatter" },
        { "System.ValueTuple`7", "RegisterValueTupleFormatter" },
        { "System.ValueTuple`8", "RegisterValueTupleFormatter" },
    };
}
